const title = "APP版";
const listData = [
    { title: 'lodding', img: 'images/list/loding.jpg' },
    { title: '彈跳視窗(每日遊戲)', img: 'images/list/DailyGame.jpg' },
    { title: '彈跳視窗(註冊贈點)', img: 'images/list/Roulette.jpg' },
    { title: '首頁輪播圖 (第1組)', img: 'images/list/index01.jpg' },
    { title: '首頁輪播圖 (第2組)', img: 'images/list/index02.jpg' },
    { title: '首頁輪播圖 (第3組)', img: 'images/list/index03.jpg' },
    { title: '已登入', img: 'images/list/Signin.jpg' },
    { title: '已登入首頁(下拉選單)', img: 'images/list/menu.jpg' },
    { title: '新聞內頁', img: 'images/list/Inside-page.jpg' },
    { title: '關於我們', img: 'images/list/about.jpg' },
    { title: '我的', img: 'images/list/mine.jpg' },
    { title: '會員登入', img: 'images/list/login.jpg' },
    { title: '忘記帳號或密碼', img: 'images/list/forget.jpg' },
    { title: '使用者規章', img: 'images/list/notice.jpg' },
    { title: '個人資料', img: 'images/list/account.jpg' },
    { title: '日曆展開', img: 'images/list/calendar.jpg' },
    { title: '修改登入/取款密碼', img: 'images/list/account-change-Password.jpg' },
    { title: '纪錄查詢', img: 'images/list/account-wallist.jpg' },
    { title: '查詢項目', img: 'images/list/member_list.jpg' },
    { title: '轉贈點數', img: 'images/list/account-wallist2.jpg' },
    { title: '最新消息', img: 'images/list/news.jpg' },
    { title: '收件箱', img: 'images/list/mail-box.jpg' },
    { title: '收件箱>信件內容', img: 'images/list/mail-box-a.jpg' },
    { title: '收件箱>寄件箱', img: 'images/list/mail-send.jpg' },
    { title: '主旨類型', img: 'images/list/mail-send-week.jpg' },
    { title: '賽事', img: 'images/list/Match.jpg' },
    { title: '廣告', img: 'images/list/event.jpg' },
    { title: '遊戲', img: 'images/list/playGame.jpg' },
    { title: '討論區', img: 'images/list/forum.jpg' },
    { title: 'app分享', img: 'images/list/app.jpg' },
    { title: '連結下載', img: 'images/list/Install.jpg' },
    { title: '安裝說明', img: 'images/list/Installnotes.jpg' }, 
]

// Inside-page